import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  interviewSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Introducción',
    },
    {
      type: 'category',
      label: '🟢 Junior',
      collapsed: false,
      link: { type: 'doc', id: 'junior/index' },
      items: [{ type: 'autogenerated', dirName: 'junior' }],
    },
    {
      type: 'category',
      label: '🟡 Semi-Senior',
      collapsed: false,
      link: { type: 'doc', id: 'semi-senior/index' },
      items: [{ type: 'autogenerated', dirName: 'semi-senior' }],
    },
    {
      type: 'category',
      label: '🔴 Senior',
      collapsed: false,
      link: { type: 'doc', id: 'senior/index' },
      items: [{ type: 'autogenerated', dirName: 'senior' }],
    },
    {
      type: 'category',
      label: '🧠 Habilidades Transversales',
      collapsed: false,
      items: [
        { type: 'doc', id: 'comportamiento-star', label: '🌟 Preguntas de Comportamiento (STAR)' },
      ],
    },
  ],
};

export default sidebars;
